--CREAR BASE DE DATOS
CREATE DATABASE PRUEBA_BRAHAN_ACOSTA

--POSICIONARSE EN LA BASE DE DATOS
USE PRUEBA_BRAHAN_ACOSTA

--CREAR TABLA 
CREATE TABLE PACIENTES(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TIPO_DOCUMENTO VARCHAR(40),
	NUMERO_DOCUMENTO INT,
	NOMBRE VARCHAR(50),
	APELLIDOS VARCHAR(50),
	CORREO_ELECTRONICO VARCHAR(50),
	TELEFONO INT,
	FECHA_NACIMIENTO DATETIME,
	ESTADO_AFILIACION VARCHAR(30)
)

INSERT INTO PACIENTES VALUES 
('CEDULA DE CIUDADANIA','32242','LAURA','AMAYA','AMAYA@GMAIL','44343','06/25/1999','ACTIVO'),
('TARJETA DE IDENTIDAD','766565','PEDRO','SANCHEZ','SANCHEZ@GMAIL','4565','09/29/1994','INACTIVO'),
('CEDULA DE CIUDADANIA','213243','PABLO','PINEDA','PINEDA@GMAIL','4332','08/09/1997','ACTIVO'),
('PASAPORTE','788799','JOHANA','LOPEZ','LOPEZ@GMAIL','677777','12/09/1999','INACTIVO')


--CREAR PROCEDIMIENTO NUEVO PACIENTE
CREATE PROC SP_NUEVO_PACIENTE
	@XTIPO_DOCUMENTO VARCHAR(50),
	@XNUMERO_DOCUMENTO INT,
	@XNOMBRE VARCHAR(50),
	@XAPELLIDOS VARCHAR(50),
	@XCORREO_ELECTRONICO VARCHAR(50),
	@XTELEFONO INT,
	@XFECHA_NACIMIENTO DATETIME,
	@XESTADO_AFILIACION VARCHAR(30)
AS
	INSERT INTO PACIENTES(
		TIPO_DOCUMENTO,
		NUMERO_DOCUMENTO,
		NOMBRE,
		APELLIDOS,
		CORREO_ELECTRONICO,
		TELEFONO,
		FECHA_NACIMIENTO,
		ESTADO_AFILIACION
	)VALUES(
		@XTIPO_DOCUMENTO,
		@XNUMERO_DOCUMENTO,
		@XNOMBRE,
		@XAPELLIDOS,
		@XCORREO_ELECTRONICO,
		@XTELEFONO,
		@XFECHA_NACIMIENTO,
		@XESTADO_AFILIACION
	)
GO

--CREAR PROCEDIMIENTO ACTUALIZAR
CREATE PROC SP_ACTUALIZAR_PACIENTE
	@XID INT,
	@XTIPO_DOCUMENTO VARCHAR(50),
	@XNUMERO_DOCUMENTO INT,
	@XNOMBRE VARCHAR(50),
	@XAPELLIDOS VARCHAR(50),
	@XCORREO_ELECTRONICO VARCHAR(50),
	@XTELEFONO INT,
	@XFECHA_NACIMIENTO DATETIME,
	@XESTADO_AFILIACION VARCHAR(30)
AS
	UPDATE PACIENTES SET
		TIPO_DOCUMENTO = @XTIPO_DOCUMENTO,
		NUMERO_DOCUMENTO = @XNUMERO_DOCUMENTO,
		NOMBRE = @XNOMBRE,
		APELLIDOS = @XAPELLIDOS,
		CORREO_ELECTRONICO = @XCORREO_ELECTRONICO,
		TELEFONO = @XTELEFONO,
		FECHA_NACIMIENTO = @XFECHA_NACIMIENTO,
		ESTADO_AFILIACION = @XESTADO_AFILIACION
		WHERE ID = @XID
		
GO

--CREAR PROCEDIMIENTO CONSULTAR
CREATE PROC SP_CONSULTAR_PACIENTE
AS
	SELECT * FROM PACIENTES 
GO

--CREAR PROCEDIMIENTO BUSCAR ID
CREATE PROC SP_BUSCAR_ID_PACIENTE
	@XID INT
AS
	SELECT * FROM PACIENTES WHERE ID = @XID
GO

--CREAR PROCEDIMIENTO ELIMINAR
CREATE PROC SP_ELIMINAR_PACIENTE
	@XID INT
AS
	DELETE PACIENTES WHERE ID = @XID
GO

--TRAER DATOS
SELECT * FROM PACIENTES

--PROBAR LOS SP
EXEC SP_NUEVO_PACIENTE 'CEDULA DE CIUDADANIA','2434242','ESTELA','ROBLES','ROBLES@GMAIL.COM','43432432','12/07/1999','ACTIVO'
EXEC SP_ACTUALIZAR_PACIENTE '9','CEDULA DE CIUDADANIA','7765','ESTELA','RONDON','RONDON@GMAIL.COM','43432432','12/07/1999','INACTIVO'
EXEC SP_CONSULTAR_PACIENTE
EXEC SP_BUSCAR_ID_PACIENTE '9'
EXEC SP_ELIMINAR_PACIENTE '9'